#
# Copyright 2021-2025 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

apiVersion: v2
name: rt-tests
description: Chart for deploying RT-Tests
kubeVersion: ">= 1.24.0-0"
icon: https://wiki.linuxfoundation.org/_media/wiki/logo.png
home: https://wiki.linuxfoundation.org/realtime/documentation/howto/tools/rt-tests
sources:
  - https://web.git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git/
keywords:
  - rt-tests
  - srsran
type: application
version: 1.0.0
appVersion: "2.8"
