apiVersion: v1
kind: Service
metadata:
  name: {{ include "metrics-server.fullname" . }}
  labels:
    {{- include "metrics-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.config.serviceType }}
  ports:
    - port: {{ .Values.config.port }}
      targetPort: srs-data-sink
      protocol: UDP
      name: data-sink
  selector:
    {{- include "metrics-server.selectorLabels" . | nindent 4 }}
