#
# Copyright 2021-2025 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

include:
  - project: softwareradiosystems/ci/tools
    ref: "21"
    file: .gitlab/ci-shared/setup/all.yml
  - project: softwareradiosystems/ci/tools
    ref: "21"
    file: .gitlab/ci-shared/tools/docker.yml

stages:
  - test
  - publish
  - manifest

.docker-builder-rt-tests:
  extends: .docker-builder
  variables:
    CONTEXT: images/rt-tests
    VERSION: "${RT_TESTS_VERSION}"
    BUILD_ARGS: "RT_TESTS_VERSION=${RT_TESTS_VERSION}"
    NAME: rt-tests
    MULTI_ARCH_BUILD: "true"
    REGISTRY_URI: ""
    REGISTRY_ORG: $PUBLIC_CT_REGISTRY_URI
  parallel:
    matrix:
      - PLATFORM: ["arm64", "amd64"]

only-build-rt-tests:
  stage: test
  extends: .docker-builder-rt-tests
  rules:
    - if: $ON_MR
  variables:
    MODE: test

build-and-publish-rt-tests:
  stage: publish
  extends: .docker-builder-rt-tests
  rules:
    - if: $ON_DEFAULT_BRANCH
    - if: $ON_MR
      when: manual
      allow_failure: true
  variables:
    MODE: publish

docker manifest:
  extends: .docker manifest
  stage: manifest
  variables:
    REGISTRY_URI: ""
    REGISTRY_ORG: $PUBLIC_CT_REGISTRY_URI
    NAME: rt-tests
    VERSION: "${RT_TESTS_VERSION}"
  needs:
    - job: build-and-publish-rt-tests
      optional: false
