#
# Copyright 2021-2025 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "influxdb3.fullname" . }}
  labels:
    app: influxdb3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb3
  template:
    metadata:
      labels:
        app: influxdb3
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: influxdb3
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOG_FILTER
              value: "{{ .Values.env.LOG_FILTER }}"
            - name: INFLUXDB_NODE_ID
              value: "{{ .Values.env.INFLUXDB_NODE_ID }}"
          command: ["influxdb3", "serve"]
          args: {{ toJson .Values.args }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            - name: plugins
              mountPath: {{ .Values.persistence.pluginMountPath }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      volumes:
        - name: data
{{- if .Values.persistence.enabled }}
{{- if .Values.persistence.hostPath }}
          hostPath:
            path: {{ .Values.persistence.hostPath }}
            type: DirectoryOrCreate
{{- else }}
          persistentVolumeClaim:
            claimName: influxdb3-pvc
{{- end }}
{{- end }}
        - name: plugins
{{- if .Values.persistence.enabled }}
{{- if .Values.persistence.hostPath }}
          hostPath:
            path: {{ .Values.persistence.hostPath }}-plugins
            type: DirectoryOrCreate
{{- else }}
          persistentVolumeClaim:
            claimName: influxdb3-plugins-pvc
{{- end }}
{{- end }}
