#
# Copyright 2021-2025 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

include:
  - project: softwareradiosystems/ci/tools
    ref: "20"
    file: .gitlab/ci-shared/setup/all.yml
  - local: .gitlab/ci/helm_utils.yml

stages:
  - static

helm lint:
  extends: .helm lint
  variables:
    CHART_PATH: charts/grafana-srsran
  before_script:
    - helm repo add influxdata https://helm.influxdata.com
