#
# Copyright 2021-2025 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

apiVersion: v2
name: grafana-deployment
description: A Helm chart to deploy Grafana for srsRAN
type: application
version: 1.3.0
appVersion: "9.2.10"

dependencies:
  - name: grafana
    repository: "https://grafana.github.io/helm-charts"
    version: "9.2.10"
    alias: grafana
  - name: telegraf
    repository: "https://helm.influxdata.com/"
    version: "1.8.60"
    alias: telegraf
  - name: influxdb3
    repository: "https://srsran.github.io/srsRAN_Project_helm/"
    version: "1.0.0"
    alias: influxdb3
