apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linuxptp.fullname" . }}
  labels:
    {{- include "linuxptp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "linuxptp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "linuxptp.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "linuxptp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostNetwork: true
      volumes:
        - name: config-volume
          configMap:
            name: linuxptp-configmap
        - name: entrypoint-volume
          configMap:
            name: linuxptp-entrypoint-configmap
            defaultMode: 0777
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command: ["/etc/entrypoint/entrypoint.sh"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: entrypoint-volume
              mountPath: /etc/entrypoint
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
