#
# Copyright 2021-2025 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

include:
  - project: softwareradiosystems/ci/tools
    ref: "22"
    file: .gitlab/ci-shared/setup/all.yml
  - project: softwareradiosystems/ci/tools
    ref: "22"
    file: .gitlab/ci-shared/tools/docker.yml

stages:
  - test
  - publish
  - manifest

variables:
  TUNED_NAME: tuned-agent

.docker-builder-tuned:
  extends: .docker-builder
  variables:
    CONTEXT: images/tuned
    VERSION: "${TUNED_VERSION}_${CT_VERSION}"
    BUILD_ARGS: "TUNED_VERSION=${TUNED_VERSION}"
    NAME: ${TUNED_NAME}
    MULTI_ARCH_BUILD: "true"
    REGISTRY_URI: ""
    REGISTRY_ORG: $PUBLIC_CT_REGISTRY_URI
  parallel:
    matrix:
      - PLATFORM: ["arm64", "amd64"]

only-build-tuned:
  stage: test
  extends: .docker-builder-tuned
  rules:
    - if: $ON_MR
  variables:
    MODE: test

build-and-publish-tuned:
  stage: publish
  extends: .docker-builder-tuned
  rules:
    - if: $ON_DEFAULT_BRANCH
    - if: $ON_MR
      when: manual
      allow_failure: true
  variables:
    MODE: publish

docker manifest ubuntu 24.04:
  extends: .docker manifest
  stage: manifest
  variables:
    REGISTRY_URI: ""
    REGISTRY_ORG: $PUBLIC_CT_REGISTRY_URI
    NAME: ${TUNED_NAME}
    VERSION: "${TUNED_VERSION}_${CT_VERSION}"
  needs:
    - job: build-and-publish-tuned
      optional: false
