apiVersion: v2
name: linuxptp
description: Chart for deploying PTP daemon on nodes
kubeVersion: ">= 1.20.0-0"
icon: https://linuxptp.nwtime.org/images/logo.png
home: https://linuxptp.nwtime.org/
sources:
- https://github.com/richardcochran/linuxptp
keywords:
- linuxptp
- ptp4l
- phc2sys
- ptp
type: application
version: 0.1.0
appVersion: "1.16.0"
