replicaCount: 1

image:
  repository: 166552988672.dkr.ecr.eu-west-1.amazonaws.com/ci/srsgnb_k8s/linuxptp
  pullPolicy: IfNotPresent
  tag: "v4.1_1.0.0"

imagePullSecrets:
  - name: regcred

nameOverride: "linuxptp-chart"
fullnameOverride: "linuxptp-chart"

serviceAccount:
  create: true
  annotations: {}
  name: "srsadmin"

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    add: ["SYS_NICE", "NET_ADMIN"]
  privileged: true
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}
  # kubernetes.io/hostname: sdr6

tolerations: {}
  # - key: "purpose"
  #   value: "retina"
  #   operator: "Equal"
  #   effect: "NoSchedule"

affinity: {}

interfaceName: "enp1s0f0"
