include:
  - project: softwareradiosystems/ci/tools
    ref: "12"
    file: .gitlab/ci-shared/setup/all.yml
  - project: softwareradiosystems/ci/tools
    ref: "12"
    file: .gitlab/ci-shared/tools/docker.yml

stages:
  - test
  - publish

.docker-builder-ubuntu-22.04:
  extends: .docker-builder
  variables:
    CONTEXT: images/Ubuntu-2204
    VERSION: "${CT_VERSION}"
    BUILD_ARGS: "CR_REGISTRY_URI=${CR_REGISTRY_URI};UHD_VERSION=${UHD_VERSION};DPDK_VERSION=${DPDK_VERSION}"
    GIT_SUBMODULE_STRATEGY: recursive
    NAME: srsran-cudu-${SRSRAN_VERSION}-${SOFTWARE_USED}-${CPU_FLAGS}
  before_script:
    - export NAME=$(echo "$NAME" | tr '[:upper:]' '[:lower:]')

only-build-amd64-avx512:
  stage: test
  extends: .docker-builder-ubuntu-22.04
  tags:
    - amd64-avx2-avx512
  rules:
    - if: $ON_MR
  variables:
    MODE: test
    CPU_FLAGS: avx512
    # EXTRA_CMAKE_ARGS: "-DAUTO_DETECT_ISA=OFF\ -DHAVE_AVX512=ON\ -DHAVE_AVX2=ON\ -DHAVE_AVX=ON\ -DHAVE_SSE=ON\ -DHAVE_FMA=ON"

build-and-publish-amd64-avx512:
  stage: publish
  extends: .docker-builder-ubuntu-22.04
  tags:
    - amd64-avx2-avx512
  rules:
    - if: $ON_DEFAULT_BRANCH
    - if: $ON_MR
      when: manual
      allow_failure: true
  variables:
    MODE: publish
    CPU_FLAGS: avx512
    # EXTRA_CMAKE_ARGS: "-DAUTO_DETECT_ISA=OFF -DHAVE_AVX512=ON -DHAVE_AVX2=ON -DHAVE_AVX=ON -DHAVE_SSE=ON -DHAVE_FMA=ON"

only-build-amd64-avx2:
  stage: test
  extends: .docker-builder-ubuntu-22.04
  rules:
    - if: $ON_MR
  variables:
    MODE: test
    CPU_FLAGS: avx2
    # EXTRA_CMAKE_ARGS: "-DAUTO_DETECT_ISA=OFF -DHAVE_AVX2=ON -DHAVE_AVX=ON -DHAVE_SSE=ON -DHAVE_FMA=ON"

build-and-publish-amd64-avx2:
  stage: publish
  extends: .docker-builder-ubuntu-22.04
  rules:
    - if: $ON_DEFAULT_BRANCH
    - if: $ON_MR
      when: manual
      allow_failure: true
  variables:
    MODE: publish
    CPU_FLAGS: avx2
    # EXTRA_CMAKE_ARGS: "-DAUTO_DETECT_ISA=OFF -DHAVE_AVX2=ON -DHAVE_AVX=ON -DHAVE_SSE=ON -DHAVE_FMA=ON"

only-build-arm64-neon:
  stage: test
  extends: .docker-builder-ubuntu-22.04
  tags:
    - arm64
  rules:
    - if: $ON_MR
  variables:
    MODE: test
    PLATFORM: arm64
    CPU_FLAGS: neon
    # EXTRA_CMAKE_ARGS: "-DHAVE_NEON=ON"

build-and-publish-arm64-neon:
  stage: publish
  extends: .docker-builder-ubuntu-22.04
  tags:
    - arm64
  rules:
    - if: $ON_DEFAULT_BRANCH
    - if: $ON_MR
      when: manual
      allow_failure: true
  variables:
    MODE: publish
    PLATFORM: arm64
    CPU_FLAGS: neon
    # EXTRA_CMAKE_ARGS: "-DHAVE_NEON=ON"
