apiVersion: v2
name: srsran-cudu
description: Official srsRAN 5G Chart
kubeVersion: ">= 1.20.0-0"
icon: https://docs.srsran.com/en/latest/_static/logo.png
home: https://docs.srsran.com/projects/project/en/latest/
sources:
- https://github.com/srsran/srsran_project
keywords:
- srsran
- 5g
- oran
- open-ran
- gnb
- mobile
type: application
version: 0.1.0
appVersion: "1.16.0"
