gnb_id: 1
amf:
  addr: 192.168.20.30                 # The address or hostname of the AMF.
  bind_addr: 192.168.20.10              # A local IP that the gNB binds to for traffic from the AMF.

ru_ofh:
  t1a_max_cp_dl: 470
  t1a_min_cp_dl: 258
  t1a_max_cp_ul: 300
  t1a_min_cp_ul: 285
  t1a_max_up: 350
  t1a_min_up: 50
#  ta4_max: 150                                                    # Maximum Ta4 on User-Plane in microseconds.
#  ta4_min: 25  
  is_prach_cp_enabled: true
  is_dl_broadcast_enabled: false
  ignore_ecpri_payload_size: true
  compr_method_ul: bfp
  compr_bitwidth_ul: 9
  compr_method_dl: bfp
  compr_bitwidth_dl: 9
  compr_method_prach: bfp
  compr_bitwidth_prach: 9
  enable_ul_static_compr_hdr: true
  enable_dl_static_compr_hdr: true
  iq_scaling: 6.5
  enable_dl_parallelization: true
  cells:
  - network_interface: enp1s0f0
    ru_mac_addr: B8:CE:F6:38:25:4B
    du_mac_addr: 00:11:22:33:44:66
    vlan_tag: 1
    prach_port_id: [8, 9]
    dl_port_id: [0, 1, 2, 3]
    ul_port_id: [0, 1, 2, 3]

cell_cfg:
  dl_arfcn: 625000                  # ARFCN of the downlink carrier (center frequency).
  band: 78                          # The NR band.
  channel_bandwidth_MHz: 100         # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                    # Subcarrier spacing in kHz used for data.
  plmn: "00101"                     # PLMN broadcasted by the gNB.
  tac: 7                            # Tracking area code (needs to match the core configuration).
  pci: 1                            # Physical cell ID.
  prach:
    prach_config_index: 159
    prach_root_sequence_index: 1
    zero_correlation_zone: 0
    prach_frequency_start: 12
  ssb:
    ssb_period: 20
  pucch:
   sr_period_ms: 20
   f1_nof_cell_res_sr: 30
  csi:
    csi_rs_period: 40
  pdsch:
   mcs_table: qam256
   nof_ports: 1
  pusch:
   mcs_table: qam256
  nof_antennas_dl: 4
  nof_antennas_ul: 1
  tdd_ul_dl_cfg:
    nof_dl_slots: 6
#    nof_dl_symbols: 7
    nof_ul_slots: 3
log:
  filename: /tmp/gnb.log            # Path of the log file.
  all_level: info                # Logging level applied to all layers.
  mac_level: debug
  phy_level: debug
#  gtpu_level: debug
#  lib_level: debug
#  cu_level: debug
#  f1ap_level: debug
#  rrc_level: debug
#  ngap_level: debug

pcap:
  mac_enable: false                 # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap   # Path where the MAC PCAP is stored.
#  ngap_enable: true                # Set to true to enable NGAP PCAPs.
#  ngap_filename: /tmp/gnb_ngap.pcap # Path where the NGAP PCAP is stored.
#  f1ap_enable: true
#  e1ap_enable: true

expert:
  enable_tuned_affinity_profile: true
  number_of_threads_per_cpu: 1
  number_of_reserved_cores: 4

expert_phy:
  nof_ul_threads: 3
  nof_pdsch_threads: 4
  nof_dl_threads: 2
  max_proc_delay: 5
  pdsch_processor_type: concurrent

hal:
  eal_args: "--lcores (0-1)@(0-15)"
