replicaCount: 1

image:
  repository: 166552988672.dkr.ecr.eu-west-1.amazonaws.com/srsgnb-k8s-ubuntu
  pullPolicy: IfNotPresent
  tag: "2023.5_0.0.4-amd64"

imagePullSecrets:
  - name: regcred

nameOverride: "srsran-project-cudu"
fullnameOverride: "srsran-project-cudu-chart"

serviceAccount:
  create: true
  annotations: {}
  name: "srsadmin-gnb"

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    add: ["SYS_NICE", "NET_ADMIN"]
  privileged: true
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 12
    memory: 16Gi
    hugepages-1Gi: 8Gi
  requests:
    cpu: 12
    memory: 16Gi
    hugepages-1Gi: 8Gi

nodeSelector: {}
#   kubernetes.io/hostname: hp-oran

tolerations: {}
  # - key: "purpose"
  #   value: "manual-testing"
  #   operator: "Equal"
  #   effect: "NoSchedule"

affinity: {}
