# ORAN plugfest Orange config
gnb_id: 1
amf:
  addr: 10.10.2.10                                                # The address or hostname of the AMF.
  bind_addr: 10.10.2.20                                           # A local IP that the gNB binds to for traffic from the AMF.  
  #no_core: true
ru_ofh:
#  ru_bandwidth_MHz: 50
#  t1a_max_cp_dl: 370                                              # Maximum T1a on Control-Plane for Downlink in microseconds.
#  t1a_min_cp_dl: 250                                              # Minimum T1a on Control-Plane for Downlink in microseconds.
#  t1a_max_cp_ul: 329                                              # Maximum T1a on Control-Plane for Uplink in microseconds.
#  t1a_min_cp_ul: 250                                              # Minimum T1a on Control-Plane for Uplink in microseconds.
#  t1a_max_up: 120                                                 # Maximum T1a on User-Plane in microseconds.
#  t1a_min_up: 80                                                  # Minimum T1a on User-Plane in microseconds.
  t1a_max_cp_dl: 450
  t1a_min_cp_dl: 250
  t1a_max_cp_ul: 450
  t1a_min_cp_ul: 250
  t1a_max_up: 120
  t1a_min_up: 0
  ta4_max: 200                                                    # Maximum Ta4 on User-Plane in microseconds.
  ta4_min: 0
  is_prach_cp_enabled: true                                       # Configures if Control-Plane messages should be used to receive PRACH messages.
  compr_method_ul: bfp                                            # Uplink compression method.
  compr_bitwidth_ul: 9                                            # Uplink IQ samples bitwidth after compression.
  compr_method_dl: bfp                                            # Downlink compression method.
  compr_bitwidth_dl: 9                                            # Downlink IQ samples bitwidth after compression.
  compr_method_prach: bfp                                     # PRACH compression method.
  compr_bitwidth_prach: 9                                     # PRACH IQ samples bitwidth after compression.
  enable_ul_static_compr_hdr: false                               # Configures if the compression header is present for uplink User-Plane messages (false) or not present (true).
  enable_dl_static_compr_hdr: false                               # Configures if the compression header is present for downlink User-Plane messages (false) or not present (true).
  iq_scaling: 1.0                                                # IQ samples scaling factor applied before compression, should be a positive value smaller than 1.
  ignore_ecpri_payload_size: true
  compr_method_prach: bfp
  compr_bitwidth_prach: 9
  cells:
    - network_interface: ens4f0                              # Ethernet interface name used to communicate with the RU.
      ru_mac_addr: 6c:ad:ad:00:05:cc                              # RU MAC address.
      du_mac_addr: 40:a6:b7:2e:0f:03                              # DU MAC address.
      #mtu: 9216
      vlan_tag: 376                                                 # VLAN tag value.
      prach_port_id: [4, 5, 6, 7]                                 # PRACH eAxC port values.
      dl_port_id: [0,1]                                    # Downlink eAxC port values.
      ul_port_id: [0, 1, 2, 3]                                    # Uplink eAxC port values.
hal:                                                              # HAL configuration.
  eal_args: "--lcores (0-1)@(0-15) -b 0000:18:00.0 -b 0000:18:00.1"                               # EAL configuration parameters used to initialize DPDK.

slicing:
  -
    sst: 1
    sd: 66051
#  -
#    sst: 1
#    sd: 1122867

cu_cp:
  rrc:
    force_reestablishment_fallback: true

cell_cfg:
  dl_arfcn: 650000                                                # ARFCN of the downlink carrier (center frequency 3.6G).
  band: 78                                                        # The NR band.
  channel_bandwidth_MHz: 60                                      # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                  # Subcarrier spacing in kHz used for data.
  plmn: "20892"                                                   # PLMN broadcasted by the gNB.
  tac: 1                                                          # Tracking area code (needs to match the core configuration).
  pci: 1                                                         # Physical cell ID.
  nof_antennas_dl: 2
  nof_antennas_ul: 1
  prach:
    prach_config_index: 159                                       # PRACH configuration index.
    prach_root_sequence_index: 1                                  # PRACH root sequence index.
    zero_correlation_zone: 0                                      # Zero correlation zone.
    prach_frequency_start: 12                                     # Offset in PRBs of lowest PRACH transmission occasion in frequency domain respective to PRB 0.
  ssb:
    ssb_period: 20  
  pucch:
   #sr_period_ms: 10
   #f1_nof_cell_res_sr: 30
   #min_k1: 2
  csi:
    #csi_rs_period: 80
  pdsch: 
   olla_target_bler: 0.1
   #min_rb_size: 15
   mcs_table: qam256
   #dc_offset: center
   #max_alloc_attempts: 6
  pusch:
   #olla_target_bler: 0.1
   #olla_max_snr_offset: 10
   mcs_table: qam256
   # max_alloc_attempts: 6
   #min_k2: 2
  ssb:
    #ssb_block_power_dbm: -30

  tdd_ul_dl_cfg:
    nof_dl_slots: 7
    nof_dl_symbols: 7
    nof_ul_slots: 2

log:
  filename: /tmp/gnb.log                                          # Path of the log file.
  all_level: warning                                              # Logging level applied to all layers.
  mac_level: info                                                # MAC log level. 
  phy_level: info                                                # PHY log level.
#  ofh_level: info                                                # OFH log level.
#  broadcast_enabled: true
#  rrc_level: info
#  cu_level: debug
#  ngap_level: debug

pcap:
  mac_enable: false                                               # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap                                 # Path where the MAC PCAP is stored.
  ngap_enable: true                                              # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap                               # Path where the NGAP PCAP is stored.

expert_execution:
 threads:
  upper_phy:
   nof_ul_threads: 1
   # nof_pusch_decoder_threads: 1
   nof_pdsch_threads: 3
   nof_dl_threads: 2
  ofh:
   enable_dl_parallelization: true
expert_phy:  
 max_proc_delay: 5


qos:
  -
    five_qi: 9
    rlc:
     mode: am
     am:
       tx:
         sn: 18
         t-poll-retransmit: 40
         max-retx-threshold: 32
         poll-pdu: 16
         poll-byte: -1
       rx:
         sn: 18
         t-reassembly: 20
         t-status-prohibit: 10
    pdcp:
      tx:
        sn: 18
        discard_timer: -1
        status_report_required: false
      rx:
        sn: 18
        t_reordering: 200
        out_of_order_delivery: false
    f1u_du:
      backoff_timer: 10
    f1u_cu_up:
      backoff_timer: 10


metrics:
  enable_json_metrics: false
  json_metrics_filename: /tmp/gnb_metrics.json
