replicaCount: 1

image:
  repository: softwareradiosystems/srsran-cu-du-ub2204
  pullPolicy: IfNotPresent
  tag: "2023.5_dpdk-23.07_avx2_1.0.2-amd64"

imagePullSecrets:
  - name: regcred

nameOverride: "srsran-project-cudu"
fullnameOverride: "srsran-project-cudu-chart"

serviceAccount:
  create: true
  annotations: {}
  name: "srsadmin-gnb"

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    add: ["SYS_NICE", "NET_ADMIN"]
  privileged: true
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 16
  #   memory: 16Gi
  #   hugepages-1Gi: 8Gi
  # requests:
  #   cpu: 16
  #   memory: 16Gi
  #   hugepages-1Gi: 8Gi

nodeSelector: {}
  # kubernetes.io/hostname: node1

tolerations: {}
  # - key: "purpose"
  #   value: "manual-testing"
  #   operator: "Equal"
  #   effect: "NoSchedule"

affinity: {}
