apiVersion: v1
kind: ConfigMap
metadata:
  name: linuxptp-configmap
data:
  linuxptp.cfg: {{ tpl (.Files.Get "linuxptp.cfg") . | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: linuxptp-entrypoint-configmap
data:
  entrypoint.sh: {{ tpl (.Files.Get "entrypoint.sh") . | quote }}